### ISSUE TITLE
Path isn’t correct (tested on macOS)

### ISSUE THREAD

**Issue by CyberFlameGO** [jacobtread/L4J-Vuln-Patch#1]
I get `ERROR: Could not find minecraft install at /Users/cyberflame/Downloads/patchypatchy/L4J-Vuln-Patch/build/libs/~/Library/Application Support/minecraft???` when trying to run the applet.

My understanding is that the applet is treating the path returned from the function(?) as a relative path, though I have limited experience with Kotlin so I’m unsure

**Comment by jacobtread** [comment]
I've modified the code a bit can you let me know if its working now? Im not too sure I cannot test on operating systems that arent windows

**Comment by CyberFlameGO** [comment]
Yep that did it! I didn’t understand the reason it wasn’t working myself honestly XD
